apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rickandmorty.fullname" . }}
  labels:
    app: {{ include "rickandmorty.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rickandmorty.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "rickandmorty.name" . }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ include "rickandmorty.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
